-- Create a table named "tweets" with the following columns:
--     id           (integer)       primary key, auto increment
--     body         (string)        max length = 140, not null
--     user         (string)        not null, corresponds to user's email
--     created_at   (timestamp)     default to current timestamp
--
-- Write your query below:
